name: firebase_storage
description: Flutter plugin for Firebase Cloud Storage, a powerful, simple, and
  cost-effective object storage service for Android and iOS.
author: Flutter Team <flutter-dev@googlegroups.com>
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_storage
version: 3.1.0

flutter:
  plugin:
    androidPackage: io.flutter.plugins.firebase.storage
    iosPrefix: FLT
    pluginClass: FirebaseStoragePlugin

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0

dev_dependencies:
  http: ^0.12.0+2
  flutter_test:
    sdk: flutter
  uuid: ^2.0.2
  flutter_driver:
    sdk: flutter
  test: any
  e2e: 0.7.0

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"
